### ISSUE TITLE
Hack.io.BTI

### ISSUE THREAD

**Issue by F1mmel** [SuperHackio/Hack.io#2]
Hello,

I just found your repo! It containts exactly what I need.
Unfortunately the description mentions that currently BTI works with all mipmaps.
Where can I download the depency? Can't find it...

Thanks!

**Comment by SuperHackio** [comment]
Unfortunately, Hack.io.BTI is in "upgrade mode" still, meaning that it has yet to be updated to .NET 8.0.
Due to that fact, it is currently unavailable. Sorry for the inconvenience.

**Comment by DragonDC1** [comment]
Thanks for your answerk. I ask because I experience strange bugs when loading the BTI. Do you know what the problem could be?

Thanks!

<img width="16" alt="U_book_04" src="https://github.com/SuperHackio/Hack.io/assets/83457170/e1edf4d8-0eeb-4bfe-9e5d-15ce60f9a040">
